In [200]:
import cv2
import numpy as np

In [201]:
image=cv2.imread('images/drawing.png')

In [202]:
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
blurred = cv2.GaussianBlur(gray, (5, 5), 0)
edges = cv2.Canny(blurred, 50, 150)

In [205]:
contours, _ = cv2.findContours(edges, cv2.CHAIN_APPROX_SIMPLE, cv2.CHAIN_APPROX_SIMPLE)
for contour in contours:
    epsilon = 0.05 * cv2.arcLength(contour, True)
    approx = cv2.approxPolyDP(contour, epsilon, True)
    
    # Check if the contour has 5 vertices (a pentagon)
    if len(approx) == 5:
        cv2.drawContours(image, [approx], 0, (0, 255, 0), 2)

In [206]:
cv2.imshow('Pentagon Detection', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [23]:
import cv2

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

ret,thresh = cv2.threshold(gray,127,255,1)

contours,h = cv2.findContours(thresh,1,2)

for cnt in contours:
    approx = cv2.approxPolyDP(cnt,0.01*cv2.arcLength(cnt,True),True)
    if len(approx)==5:
        print("pentagon")
    elif len(approx)==4:
        print("rectangle")

pentagon


error: OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\highgui\src\window.cpp:967: error: (-215:Assertion failed) size.width>0 && size.height>0 in function 'cv::imshow'


In [66]:

pentagons = []

for contour in contours:
    # Approximate the contour to a polygon
    epsilon = 0.04 * cv2.arcLength(contour, True)
    approx = cv2.approxPolyDP(contour, epsilon, True)
    
    # Check if the contour has 5 sides (pentagon)
    if len(approx) == 5:
        pentagons.append(approx)


In [71]:
edges = cv2.Canny(gray, 50, 150)

# Perform Hough Line Transform
lines = cv2.HoughLinesP(edges, 1, np.pi/180, threshold=10, minLineLength=50, maxLineGap=10)

# Draw lines on the image
if lines is not None:
    # Draw lines on the image
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

    # Display the image with lines
    cv2.imshow('Lines', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("No lines detected.")

In [227]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('images/drawing.png')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edges = cv2.Canny(gray, 50, 150)

# Perform Hough Line Transform
lines = cv2.HoughLinesP(edges,3, np.pi/180, threshold=50, minLineLength=20, maxLineGap=50)

# Check if lines are detected
if lines is not None:
    # Draw lines on the image
    for line in lines:
        x1, y1, x2, y2 = line[0]
        cv2.line(image, (x1, y1), (x2, y2), (0, 0, 255), 2)

    # Display the image with lines
    cv2.imshow('Lines', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("No lines detected.")


In [75]:
len(lines)

26

In [115]:
import cv2
import numpy as np

# Load the image
image = cv2.imread('images/drawing.png')

# Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Apply Canny edge detection
edges = cv2.Canny(gray, 50, 150)

# Perform Hough Line Transform
lines = cv2.HoughLinesP(edges, 1, np.pi / 180, threshold=100, minLineLength=50, maxLineGap=10)

# Calculate angles between lines
angles = []
for i in range(len(lines)):
    for j in range(i + 1, len(lines)):
        x1_i, y1_i, x2_i, y2_i = lines[i][0]
        x1_j, y1_j, x2_j, y2_j = lines[j][0]
        
        # Calculate the angle using the arctan function
        angle = np.arctan2((y2_i - y1_i), (x2_i - x1_i)) - np.arctan2((y2_j - y1_j), (x2_j - x1_j))
        
        # Convert the angle to degrees
        angle = np.degrees(angle)
        
        # Ensure the angle is positive
        if angle < 0:
            angle += 180
        
        # Add the angle to the list
        angles.append(angle)

# Identify angles within a certain range
desired_angles = []  # List to store desired angles
angle_threshold = 10  # Threshold for angle difference

for angle in angles:
    # Check if the angle is within the desired range
    if angle > 90 - angle_threshold and angle < 90 + angle_threshold:
        desired_angles.append(angle)

# Display the identified angles
for angle in desired_angles:
    print(f"Identified angle: {angle}")

# Display the image with lines
cv2.imshow('Lines', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [229]:
arr = np.array([1,2,5,4,6,8,3,2,1,4,5,7,8,562, 1, 2, 4,5]) 
print(arr.reshape(3,-1). shape)

(3, 6)


In [241]:
import pandas as pd
df = pd.DataFrame({'P1':[18, 20, 30], 'P2':[["A", "B", "C"],["A", "D", "E"],["C", "D", "F"]]})
df['P3'] = df ["P2"].apply(lambda x:" ".join(["_".join(i.split(" ")) for i in x]))
print(df['P3'])

0    A B C
1    A D E
2    C D F
Name: P3, dtype: object


In [242]:
import pandas as pd
df = pd.DataFrame([[15, 12],
                    [33, 54],
                    [10, 32]],
                    index = ['one', 'two', 'three'], 
                    columns = ['col1', 'col2'])
print(df.filter(regex = 'e$', axis= 0).shape)
print(df.filter(regex = '^c', axis = 1). shape)

(2, 2)
(3, 2)


In [244]:
import numpy as np
mat1 = np.array([[ 0, 1,2,3],
                 [4,5,6,7],
                 [8,9,10,11]])

indA= np.array([[2,2], [1, 1]])
indB = np.array([[2,1], [1,0]])
mat1[indA, indB] = np.array([[100, 90],[50, 40]])
print(mat1)

[[  0   1   2   3]
 [ 40  50   6   7]
 [  8  90 100  11]]


In [245]:
import pandas as pd
df = pd.DataFrame([[np.nan, 2, np.nan, 0],
                    [3, 4, np.nan, 1],
                    [np.nan, np.nan, np.nan, 5]], 
                    columns=list('ABCD'))
df.cumsum(axis=1)
df.dropna (axis = 1, how = 'all')
print(df.dropna (axis = 1, how='any'))

   D
0  0
1  1
2  5
