In [1]:
import cv2
import numpy as np

In [2]:
import cv2
import numpy as np

def extract_and_visualize_circles(image_path):
    # Read the image
    image = cv2.imread(image_path)

    # Convert the image to grayscale
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Apply image processing to detect circles
    circles = cv2.HoughCircles(
        gray,
        cv2.HOUGH_GRADIENT,
        dp=1,
        minDist=50,
        param1=50,
        param2=30,
        minRadius=10,
        maxRadius=30
    )
    coordinates = {}
    if circles is not None:
        # Convert the circle parameters to integers
        circles = np.round(circles[0, :]).astype("int")

        # Iterate through each circle
        for i, (x, y, r) in enumerate(circles):
            # Create a mask to extract the current circle
            mask = np.zeros_like(gray)
            cv2.circle(mask, (x, y), r, 255, -1)
            extracted_circle = cv2.bitwise_and(image, image, mask=mask)

            # Display the extracted circle
            cv2.imshow(f"Circle {i+1}", extracted_circle)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
            number = int(input())  # Assuming the number is the pixel value at the circle center
            coordinates[number] = (x, y)
        return coordinates
    
# Provide the path to your image
image_path = "images/2.jpg"

# Call the function to extract and visualize the circles
coordinates=extract_and_visualize_circles(image_path)


24
20
18
4
13
21
3
15
10
22
19
7
6
16
11
17
12
9
25
1
23
2
14
5
8


In [3]:
data_2=coordinates

In [4]:
import json
f = open('image_data.json')
dictionary = json.load(f)
f.close()

In [20]:
for i in dictionary['2']:
    print(i)

24
20
18
4
13
21
3
15
10
22
19
7
6
16
11
17
12
9
25
1
23
2
14
5
8


In [23]:
import json
with open("image_data.json", "w") as outfile:
    json.dump(dictionary, outfile)

In [22]:
dictionary={'1': {'19': [271, 680],
  '23': [271, 138],
  '17': [326, 483],
  '20': [381, 729],
  '8': [326, 335],
  '24': [106, 286],
  '7': [381, 138],
  '13': [161, 188],
  '10': [216, 630],
  '25': [51, 434],
  '14': [106, 89],
  '15': [216, 40],
  '3': [161, 433],
  '12': [161, 335],
  '22': [601, 385],
  '18': [435, 581],
  '16': [436, 88],
  '21': [600, 680],
  '5': [545, 482],
  '6': [546, 236],
  '2': [436, 385],
  '11': [51, 680],
  '4': [491, 679],
  '1': [546, 89],
  '9': [216, 532]},
 '2': {24: [262, 664],
  '20': [88, 192],
  '18': [270, 182],
  '4': [572, 682],
  '13': [458, 294],
  '21': [106, 362],
  '3': [458, 594],
  '15': [298, 294],
  '10': [742, 158],
  '22': [98, 508],
  '19': [192, 118],
  '7': [646, 418],
  '6': [722, 494],
  '16': [232, 408],
  '11': [646, 48],
  '17': [152, 294],
  '12': [530, 120],
  '9': [646, 252],
  '25': [298, 476],
  '1': [414, 402],
  '23': [148, 626],
  '2': [530, 476],
  '14': [382, 78],
  '5': [666, 604],
  '8': [720, 334]}}

In [29]:
def extract_and_visualize_circles(image_path):
    image = cv2.imread(image_path)
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    circles = cv2.HoughCircles(
        gray,
        cv2.HOUGH_GRADIENT,
        dp=1,
        minDist=50,
        param1=50,
        param2=30,
        minRadius=10,
        maxRadius=30
    )
    if circles is not None:
        circles = np.round(circles[0, :]).astype("int")
        for (x, y, r) in circles:
            cv2.circle(image, (x, y), r, (0, 255, 0), 2)
#             cv2.putText(image, str(r), (x - 10, y), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 0, 255), 2)
    cv2.imshow("Circles", image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [30]:
image_path = "images/1.png"
extract_and_visualize_circles(image_path)

In [35]:
image = cv2.imread('images/2.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
_, thresholded = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
contours, _ = cv2.findContours(thresholded, cv2.CHAIN_APPROX_SIMPLE, cv2.CHAIN_APPROX_NONE)

for i, contour in enumerate(contours):
        if i % 2 == 0:
            color = (0, 0, 255)  # Red color for even contours
        else:
            color = (255, 0, 0)  # Blue color for odd contours

        cv2.drawContours(image, [contour], -1, color, 2)
cv2.imshow('Image with Alternate Colored Contours', image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
circles

NameError: name 'circles' is not defined

In [26]:
dictionary[image_path[7]]=data_1

In [28]:
dictionary

{1: {19: (271, 680),
  23: (271, 138),
  17: (326, 483),
  20: (381, 729),
  8: (326, 335),
  24: (106, 286),
  7: (381, 138),
  13: (161, 188),
  10: (216, 630),
  25: (51, 434),
  14: (106, 89),
  15: (216, 40),
  3: (161, 433),
  12: (161, 335),
  22: (601, 385),
  18: (435, 581),
  16: (436, 88),
  21: (600, 680),
  5: (545, 482),
  6: (546, 236),
  2: (436, 385),
  11: (51, 680),
  4: (491, 679),
  1: (546, 89),
  9: (216, 532)},
 '1': {19: (271, 680),
  23: (271, 138),
  17: (326, 483),
  20: (381, 729),
  8: (326, 335),
  24: (106, 286),
  7: (381, 138),
  13: (161, 188),
  10: (216, 630),
  25: (51, 434),
  14: (106, 89),
  15: (216, 40),
  3: (161, 433),
  12: (161, 335),
  22: (601, 385),
  18: (435, 581),
  16: (436, 88),
  21: (600, 680),
  5: (545, 482),
  6: (546, 236),
  2: (436, 385),
  11: (51, 680),
  4: (491, 679),
  1: (546, 89),
  9: (216, 532)}}

In [27]:
# Read the image
image = cv2.imread('images/1.png')

    # Convert the image to grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
circles = cv2.HoughCircles(
        gray,
        cv2.HOUGH_GRADIENT,
        dp=1,
        minDist=50,
        param1=50,
        param2=30,
        minRadius=10,
        maxRadius=30
    )

In [28]:
for circle in circles:
    print(circle)

[[381.5 138.5  13.1]
 [216.5  40.5  13. ]
 [271.5 680.5  13. ]
 [216.5 630.5  13.2]
 [106.5 286.5  12.9]
 [271.5 138.5  13.2]
 [381.5 729.5  13.2]
 [546.5  89.5  13. ]
 [326.5 335.5  12.7]
 [600.5 385.5  13. ]
 [435.5  89.5  13.2]
 [ 51.5 434.5  12.7]
 [106.5  89.5  12.5]
 [217.5 531.5  11.8]
 [545.5 237.5  13.2]
 [ 51.5 680.5  12.9]
 [161.5 433.5  12.9]
 [491.5 679.5  12.2]
 [436.5 384.5  13.4]
 [545.5 482.5  13. ]
 [600.5 680.5  12.9]
 [326.5 483.5  12.5]
 [436.5 581.5  12.2]
 [162.5 187.5  12. ]
 [161.5 334.5  12.2]]
